import { useEffect, useState } from "react";
import { ApiError, api } from "../services/api";

interface SettingsData { email: string; name: string; memory_mode: "auto" | "ask"; memory_globally_enabled: boolean; memory_top_k: number; memory_threshold: number; custom_instructions: string }
export default function Settings() {
  const [form, setForm] = useState<SettingsData | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { void api<SettingsData>("/me").then(setForm).catch(() => setNotice("Could not load settings.")); }, []);
  if (!form) return <p className="text-mute">Loading settings…</p>;
  const change = <K extends keyof SettingsData>(key: K, value: SettingsData[K]) => setForm({ ...form, [key]: value });
  const save = async () => { try { await api<SettingsData>("/me/settings", { method: "PATCH", body: JSON.stringify(form) }); setNotice("Settings saved."); } catch (error) { setNotice(error instanceof ApiError ? error.message : "Could not save settings."); } };
  const exportData = async () => { const data = await api<Record<string, unknown>>("/me/export"); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "memoryai-export.json"; link.click(); URL.revokeObjectURL(url); };
  const deleteAccount = async () => { if (!window.confirm("Delete your account and all data? This cannot be undone.")) return; await api("/me", { method: "DELETE" }); window.location.assign("/login"); };
  return <div className="max-w-2xl space-y-6"><div><h1 className="text-2xl font-semibold">Settings</h1><p className="mt-1 text-sm text-mute">Control your account, memory, and privacy.</p></div><section className="space-y-4 rounded-xl border border-line bg-card p-5"><h2 className="font-medium">Profile</h2><label className="block text-sm">Name<input value={form.name} onChange={(event) => change("name", event.target.value)} className="mt-1 w-full rounded-lg border border-line bg-bg px-3 py-2" /></label><p className="text-sm text-mute">{form.email}</p></section><section className="space-y-4 rounded-xl border border-line bg-card p-5"><h2 className="font-medium">Memory</h2><label className="flex items-center justify-between gap-4 text-sm"><span>Enable memory globally<br/><span className="text-mute">Turning this off stops retrieval and saving for every chat.</span></span><input type="checkbox" checked={form.memory_globally_enabled} onChange={(event) => change("memory_globally_enabled", event.target.checked)} /></label><label className="block text-sm">Save mode<select value={form.memory_mode} onChange={(event) => change("memory_mode", event.target.value as "auto" | "ask")} className="mt-1 block rounded-lg border border-line bg-bg px-3 py-2"><option value="auto">Save automatically</option><option value="ask">Review suggestions first</option></select></label><label className="block text-sm">Memories retrieved: {form.memory_top_k}<input type="range" min="1" max="10" value={form.memory_top_k} onChange={(event) => change("memory_top_k", Number(event.target.value))} className="mt-2 block w-full"/></label><label className="block text-sm">Custom instructions<textarea value={form.custom_instructions} onChange={(event) => change("custom_instructions", event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-line bg-bg px-3 py-2" /></label></section><button onClick={() => void save()} className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-accent-ink">Save settings</button>{notice && <p className="text-sm text-mute">{notice}</p>}<section className="rounded-xl border border-rose-500/30 bg-card p-5"><h2 className="font-medium text-rose-600 dark:text-rose-400">Data & privacy</h2><div className="mt-3 flex flex-wrap gap-3"><button onClick={() => void exportData()} className="rounded-lg border border-line px-3 py-2 text-sm">Export my data</button><button onClick={() => void deleteAccount()} className="rounded-lg border border-rose-500/50 px-3 py-2 text-sm text-rose-600 dark:text-rose-400">Delete account</button></div></section></div>;
}
